package deduction;

import java.lang.Number;

rule "check_salary_allowed"
	dialect "mvel"
	ruleflow-group "salary"
	when
		emp : Employee( )
		request : DeductionRequest( amount < ( emp.getSalary() ) )
	then
		request.setRequestStatus( "Allowed" );
end

rule "check_salary_not_allowed"
	dialect "mvel"
	ruleflow-group "salary"
	when
		emp : Employee( )
		request : DeductionRequest( amount >= ( emp.getSalary() ) )
		ruleValidation : RuleValidation()
	then
	    ruleValidation.addValidationRule("rule02");
		request.setRequestStatus( "Not Allowed" );
end


rule "check_fitness_time"
	dialect "mvel"
	ruleflow-group "salary"
	when
		emp : Employee ( fitnessTimeLastYear == "Yes" )
		request : DeductionRequest( deductionType =="Fitness Time" && donateTo == "Legam com" ) )
		ruleValidation : RuleValidation()
	then
	    ruleValidation.addValidationRule("rule03");
		request.setRequestStatus( "Not Allowed" );
end