package deduction;

import java.util.HashMap;
import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RuleValidation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private Map<String, String> englishMessages = new HashMap<String, String>();
   private Map<String, String> arabicMessages = new HashMap<String, String>();

   private java.lang.String key;

   private java.lang.String message;

   private java.lang.String language = "en";

   public RuleValidation()
   {
      englishMessages.put("rule01", "Error while fetching your data, Please try again later");
      arabicMessages.put("rule01", "عذرا حصل خطا اثناء محاولة استعادة بياناتك, الرجاء المحاولة في وقت لاحق");

      englishMessages.put("rule02", "Deduction amount cannot be greater than net salary");
      arabicMessages.put("rule02", "المبلغ المراد خصمه لا يمكن ان يكون اكبر من اجمالي الراتب");

      englishMessages.put("rule03", "");
      arabicMessages.put("rule03", "");

      englishMessages.put("rule04", "");
      arabicMessages.put("rule04", "");
   }

   public java.lang.String getKey()
   {
      return this.key;
   }

   public void setKey(java.lang.String key)
   {
      this.key = key;
      this.message = language.equals("ar") ? arabicMessages.get(key) : englishMessages.get(key);
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public java.lang.String getLanguage()
   {
      return this.language;
   }

   public void setLanguage(java.lang.String language)
   {
      this.language = language;
   }

   public RuleValidation(java.lang.String key, java.lang.String message,
         java.lang.String language)
   {
       this();
      this.key = key;
      this.message = message;
      this.language = language;
   }

}