package deduction;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidationMessage implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ValidationMessage() {
    }

}